spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
#    url: jdbc:mysql://localhost:3306/phone_db
#    username: root
#    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: true

telegram:
  bot:
    username: ${TELEGRAM_BOT_USERNAME} #"@OldPhoneBot"
    token: ${TELEGRAM_BOT_TOKEN} #"8163853097:AAGpjtmupYG4rjeCNcV5xq5z4e2ltTCBKeU"

admin:
  password: ${ADMIN_PASSWORD}  #"Java2023"

server:
  port: ${PORT}
